# --------------------------
# Services
# -------------------------- 
services:
  # Jenkins Services 
  jenkins:
    image: my-jenkins-docker    
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "${JENKINS_PORT}:8080"
      - "50000:50000"
    volumes: 
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

  # Sonarqube Services
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - "${SONARQUBE_PORT}:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - jenkins

# --------------------------
# Networks
# --------------------------
networks:
  jenkins:
    driver: bridge
    external: true
    

# --------------------------
# Volumes
# --------------------------
volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: